fixed name of package

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -198,7 +198,7 @@ jobs:
             adb -s emulator-5554 install -t -g ./ApiDemos-debug.apk
 
             echo "Checking packages on emulator 5554:"
-            adb -s emulator-5554 shell pm list packages | grep calculator || echo "Package not found on emulator 5554"
+            adb -s emulator-5554 shell pm list packages | grep io.appium.android.apis || echo "Package not found on emulator 5554"
 
             dotnet vstest ./Ocaramba.Tests.Appium/bin/Release/net8.0/Ocaramba.Tests.Appium.dll --logger:"trx;LogFileName=Ocaramba.Tests.Appium.xml"
             echo "Closing connection with emulator-5554"
