Update github-actions.yml

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -174,31 +174,28 @@ jobs:
         run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
+         sudo udevadm trigger --name-match=kvm
+      - run: |
+          npm install -g appium
+          appium -v
+          appium driver list --installed
+          appium driver install uiautomator2
+          nohup appium --log-level warn --log-timestamp --local-timezone > appium.log 2>&1 &
+          sleep 10
+          curl http://127.0.0.1:4723/wd/hub/sessions || echo "Appium check failed"   
       - name: run tests
         uses: reactivecircus/android-emulator-runner@v2
         with:
-          api-level: 30
+          api-level: 28
           target: google_apis
           arch: x86_64
-          profile: pixel_4
+          profile: Nexus 6
           emulator-options: "-no-window -no-audio -no-snapshot"
           disable-animations: true    
           script: |
-            adb wait-for-device       
-            A=$(adb shell getprop sys.boot_completed | tr -d '\r')
-            while [ "$A" != "1" ]; do
-                    sleep 2
-                    A=$(adb shell getprop sys.boot_completed | tr -d '\r')
-            done   
-            export ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL=1200
-            sleep 1200
-            adb devices
-            npm install -g appium
-            echo "Starting Appium server..."
-            appium --log-level info &
-            sleep 10 # Wait for Appium server to start
-            echo "Appium server started."
             dotnet test ./Ocaramba/Ocaramba.Tests.Appium/Ocaramba.Tests.Appium.csproj --logger:trx || echo "Tests failed"
+            echo "Closing connection with emulator-5554"
+            adb -s emulator-5554 emu kill || true
       - name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action/linux@v2
         if: true
